const REASON = {
  NSFW_DETECTED: 'NSFW_DETECTED',
  ANIMAL_DETECTED: 'ANIMAL_DETECTED',
  NO_ANIMAL: 'NO_ANIMAL',
  NSFW_CHECK_FAILED: 'NSFW_CHECK_FAILED',
  ANIMAL_CHECK_FAILED: 'ANIMAL_CHECK_FAILED',
  MODELS_NOT_READY: 'MODELS_NOT_READY',
  INVALID_IMAGE: 'INVALID_IMAGE',
};

const STAGE_STATUS = {
  PASSED: 'passed',
  FAILED: 'failed',
  SKIPPED: 'skipped',
  ERROR: 'error',
};

const DETECTION_SOURCE = {
  OBJECT: 'object',
  SCENE: 'scene',
};

module.exports = {
  REASON,
  STAGE_STATUS,
  DETECTION_SOURCE,
};
